# Generated by Django 5.1.3 on 2024-11-20 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Atleta')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome do Atleta')),
                ('apelido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sobrenome do Atleta')),
                ('altura', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('alcance', models.FloatField(blank=True, null=True, verbose_name='Altura')),
                ('modalidade', models.IntegerField(choices=[(1, 'MMMA'), (2, 'Kickboxing')], default=1, verbose_name='Modalidade que compete')),
                ('posicao', models.IntegerField(choices=[(1, 'Destro'), (2, 'Canhoto'), (3, 'Ambidestro')], default=1, verbose_name='Posição')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('estreia', models.DateField(blank=True, null=True, verbose_name='Data de Estreia')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está em atividade?')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['modalidade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.ImageField(upload_to='projetos', verbose_name='Imagem')),
                ('tipo', models.IntegerField(choices=[(1, 'Frontal'), (2, 'Corpo'), (3, 'Outro')], default=1, verbose_name='Tipo de Imagem')),
                ('atleta', models.ForeignKey(help_text='Atleta associado', on_delete=django.db.models.deletion.CASCADE, to='punchinthehead.atleta', verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['atleta__sobrenome', 'atleta__nome', 'tipo'],
            },
        ),
    ]
