# Generated by Django 5.1.3 on 2024-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchinthehead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código do Atleta'),
        ),
    ]
