# Generated by Django 5.1.3 on 2024-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchinthehead', '0002_atleta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Frontal'), (2, 'Corpo'), (3, 'Meio Corpo'), (4, 'Outro')], default=1, verbose_name='Tipo de Imagem'),
        ),
    ]
