name: Deploy em uma VM do Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Código de check-out
        uses: actions/checkout@v3

      - name: Configurando credenciais do Google Cloud
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | base64 --decode > /tmp/gcp_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp_key.json"

      - name: Configurando Chave SSH
        run: |
          echo "$GCP_SSH_KEY" > /tmp/gcp_ssh_key
          chmod 600 /tmp/gcp_ssh_key

      - name: Definindo variáveis ​​de ambiente em app.yaml e .env na VM
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << 'EOF'
            cd /home/humildadevps/punchInTheHead/
            git checkout .
            git pull origin main -f
            rm /home/humildadevps/punchInTheHead/backend/.env
            echo "CONTAINER_BACKEND_NAME=${{ secrets.CONTAINER_BACKEND_NAME }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "CONTAINER_DB_NAME=${{ secrets.CONTAINER_DB_NAME }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "DEBUG=${{ secrets.DEBUG }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> /home/humildadevps/punchInTheHead/backend/.env
            echo "GCP_VM_IP=${{ secrets.GCP_VM_IP }}" >> /home/humildadevps/punchInTheHead/backend/.env
            docker compose up --build -d
          EOF
      - name: Build do Frontend na VM do Google Cloud
        run: |
          cd /home/humildadevps/punchInTheHead/frontend
          npm install
          npm run build --prod

      - name: Deploy do Frontend na VM do Google Cloud
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << EOF
            cd /home/humildadevps/punchInTheHead/frontend
            rm -rf dist/punchinthehead
            rsync -avz dist/punchinthehead/ humildadevps@$GCP_VM_IP:/var/www/punchinthehead/frontend
          EOF  
  
      - name: Implantação do Backend na VM do Google Cloud
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/gcp_ssh_key humildadevps@$GCP_VM_IP << EOF
            cd /home/humildadevps/punchInTheHead/backend
            rm -rf venv/
            python -m venv venv
            source venv/bin/activate
            sleep 5
            docker ps
            pip install -r requirements.txt --no-cache
            rm -rf punchinthehead/backend/static/*
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
      - name: Limpando a chave e as credenciais SSH
        run: |
          rm -f /tmp/gcp_ssh_key
          rm -f /tmp/gcp_key.json
        if: always()

    env:
      GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      GCP_SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}